modLoader = 'lowcodefml'
loaderVersion="[47,)"
license="MIT"
[[mods]] #mandatory
modId="tcpl"
version="0.1.0"
displayName="T.E.B.L. Slashblades"
authors="EverlaPrismerAya, SF2403"
description='''Added some slashblade from the end battle line'''
[[dependencies.tcpl]] #optional
   # the modid of the dependency
   modId="forge"
   mandatory=true #mandatory
   versionRange="[47,)" #mandatory
   ordering="NONE"
   side="BOTH"# Here's another dependency
[[dependencies.tcpl]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.tcpl]]
   modId="slashblade"
   mandatory=true
   versionRange="[1.1.5,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.tcpl]]
   modId="slashblade_addon"
   mandatory=true
   versionRange="[1.1.6,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.tcpl]]
   modId="mekanism"
   mandatory=false
   versionRange="[10.4.11,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.tcpl]]
   modId="srelic"
   mandatory=false
   versionRange="[2.1,)"
   ordering="NONE"
   side="BOTH"
